// 六层轨迹清洗的共享配置(默认阈值 + 归一化函数)。
//
// 从 sixLayerTrackProduct.mjs(批处理引擎)抽出,使**流式引擎不再 import 批处理**——
// 流式的 baseKernel / metricAccumulator / scenarioRecognizer 只需要 normalizeSixLayerTrackConfig
// 来填充默认阈值,不需要任何批处理清洗逻辑。抽到这里后:
//   - 流式引擎对批处理零依赖,可独立抽包 / 移植(设备端 Rust track-sdk 等)。
//   - 批处理与流式共用同一份默认阈值常量(两者场景门必须一致),单一事实来源。
// 纯原始值 + 纯函数,无外部依赖,任何语言可直译。
export const DEFAULT_SIX_LAYER_TRACK_CONFIG = Object.freeze({
  maxIntakeAccuracyMeters: 80,
  weakCloudAccuracyMeters: 30,
  firstFixGoodAccuracyMeters: 20,
  firstFixRelaxedAccuracyMeters: 30,
  gapSeconds: 120,
  recoveryCloudMinSamples: 2,
  recoveryFastPathAccuracyMeters: 10,
  recoveryFastPathMaxSpeedMetersPerSecond: 2.5,
  stationarySessionCollapseEnabled: true,
  stationarySessionMinRawPoints: 20,
  stationarySessionMinDurationSeconds: 60,
  stationarySessionMaxBboxMeters: 80,
  stationarySessionMaxNetDistanceMeters: 80,
  stationarySessionMaxPathRateMetersPerSecond: 0.05,
  stationarySessionMinSpeedSampleRatio: 0.8,
  stationarySessionMinZeroSpeedRatio: 0.95,
  stationarySessionMaxAverageReportedSpeedMetersPerSecond: 0.3,
  zeroSpeedThresholdMetersPerSecond: 0.1,
  stillMotionMaxAccelRms: 0.08,
  stillMotionMaxGyroRms: 0.03,
  stationaryDualClusterDriftEnabled: true,
  stationaryDualClusterMinRawPoints: 30,
  stationaryDualClusterMinDurationSeconds: 60,
  stationaryDualClusterMinStillMotionRatio: 0.7,
  stationaryDualClusterMinClusterShare: 0.2,
  stationaryDualClusterMinCenterDistanceMeters: 30,
  stationaryDualClusterMaxCenterDistanceMeters: 150,
  stationaryDualClusterMaxBboxMeters: 160,
  stationaryDualClusterMinTransitions: 6,
  stationaryDualClusterMinFastTransitionRatio: 0.25,
  stationaryDualClusterFastTransitionSpeedMetersPerSecond: 12,
  stationaryDualClusterMaxMovingMotionRatio: 0.35,
  stationaryDualClusterMaxAverageReportedSpeedMetersPerSecond: 0.8,
  dwellDriftCollapseEnabled: true,
  dwellDriftCoreAccuracyMeters: 30,
  dwellDriftMinCoreSamples: 10,
  dwellDriftMinRawPoints: 20,
  dwellDriftMinDurationSeconds: 60,
  dwellDriftMaxCoreGapSeconds: 60,
  dwellDriftMaxExtensionGapSeconds: 10,
  dwellDriftMaxExtensionPathMeters: 40,
  dwellDriftMaxReportedSpeedMetersPerSecond: 1.6,
  dwellDriftMaxAverageSpeedMetersPerSecond: 1.0,
  dwellDriftMinCoreRatio: 0.25,
  dwellDriftMinZeroSpeedRatio: 0.3,
  dwellDriftMaxBboxMeters: 100,
  dwellDriftMaxNetDistanceMeters: 80,
  weakRecoveryShapePreserveEnabled: true,
  weakRecoveryShapeMinSamples: 3,
  weakRecoveryShapeMaxRadiusMeters: 25,
  weakRecoveryShapeMinDistanceFromTrustedMeters: 50,
  weakRecoveryShapeMaxBestAccuracyMeters: 35,
  weakRecoveryShapeExtensionGapSeconds: 500,
  weakRecoveryShapeExtensionDistanceMeters: 130,
  weakRecoveryShapeMaxExtensionSamples: 5,
  roundTripLineSimplifyEnabled: true,
  roundTripLineMinTrackPoints: 20,
  roundTripLineMaxEndpointDistanceMeters: 6,
  roundTripLineMinTurnDistanceMeters: 80,
  roundTripLineMaxCrossTrackMeters: 35,
  roundTripLineMaxRawPointIdSpanBefore: 240,
  roundTripLineMaxRawPointIdSpanAfter: 300,
  roundTripLineSimplifyToleranceMeters: 3,
  roundTripLineSameRoadFallbackSimplifyToleranceMeters: 6,
  roundTripLineNoIntentMaxDurationSeconds: 1200,
  roundTripLineNoIntentMaxSampleGapSeconds: 600,
  roundTripSameRoadCollapseEnabled: true,
  roundTripSameRoadMaxBboxMeters: 80,
  roundTripSameRoadMaxApproachPairDistanceMeters: 35,
  roundTripSameRoadNoIntentMaxBboxMeters: 40,
  roundTripSameRoadNoIntentMaxApproachPairDistanceMeters: 20,
  roundTripSameRoadNoIntentMaxDurationSeconds: 1200,
  roundTripSameRoadNoIntentMaxSampleGapSeconds: 600,
  closedLoopRoundTripEnabled: true,
  closedLoopRoundTripMinTrackPoints: 30,
  closedLoopRoundTripMaxTrackPoints: 180,
  closedLoopRoundTripMinPathMeters: 120,
  closedLoopRoundTripMinBboxMeters: 30,
  closedLoopRoundTripMaxBboxMeters: 250,
  closedLoopRoundTripMaxEndpointDistanceMeters: 8,
  closedLoopRoundTripMaxNetPathRatio: 0.08,
  closedLoopRoundTripMaxRawPointIdSpan: 900,
  enclosedGapClusterEnabled: true,
  enclosedGapClusterMinGapRecoveries: 3,
  enclosedGapClusterMinStationaryAnchors: 3,
  enclosedGapClusterMaxBboxMeters: 90,
  enclosedGapClusterMinDurationSeconds: 300,
  enclosedGapClusterMinRawPointIdSpan: 200,
  enclosedLoopSettlementEnabled: true,
  enclosedLoopSettlementMaxBboxMeters: 90,
  enclosedLoopSettlementMaxCorridorDistanceMeters: 16,
  enclosedLoopSettlementMinRemovedTrackPoints: 6,
  restPhotoMicroMoveEnabled: true,
  restPhotoMicroMoveMinTrackPoints: 8,
  restPhotoMicroMoveMaxTrackPoints: 25,
  restPhotoMicroMoveMinPathMeters: 20,
  restPhotoMicroMoveMaxPathMeters: 120,
  restPhotoMicroMoveMaxBboxMeters: 25,
  restPhotoMicroMoveMaxEndpointDistanceMeters: 12,
  restPhotoMicroMoveMinPathNetRatio: 4,
  restPhotoMicroMoveMaxDurationSeconds: 300,
  restPhotoMicroMoveMinLowSpeedRatio: 0.8,
  restPhotoMicroMoveSimplifyEnabled: true,
  restPhotoMicroMoveSimplifyMinDurationSeconds: 60,
  restPhotoMicroMoveSimplifyToleranceMeters: 6,
  restPhotoMicroMoveSimplifyMinPathReductionRatio: 0.25,
  restPhotoMicroMoveSimplifyMaxOutputTrackPoints: 6,
  restPhotoMicroMoveCollapseMaxBboxMeters: 25,
  restPhotoMicroMoveCollapseMaxNetDistanceMeters: 12,
  restPhotoMicroMoveCollapseMaxPathMeters: 70,
  restPhotoMicroMoveLongCollapseMinDurationSeconds: 180,
  restPhotoMicroMoveLongCollapseMaxBboxMeters: 28,
  restPhotoMicroMoveLongCollapseMaxNetDistanceMeters: 10,
  restPhotoMicroMoveLongCollapseMaxPathMeters: 120,
  restPhotoMicroMoveShapeFilterMaxPathMeters: 32,
  restPhotoMicroMoveShapeFilterMaxTrackPoints: 10,
  restPhotoMicroMoveShapeFilterMaxDurationSeconds: 150,
  restPhotoMicroMoveShapeFilterMaxEdgeMeters: 6,
  restPhotoMicroMoveShapeFilterMinAnchorDetourMeters: 12,
  movingSpikeCleanupEnabled: true,
  movingSpikeMaxReportedSpeedMetersPerSecond: 0.2,
  movingSpikeMaxCompetingReportedSpeedMetersPerSecond: 1.0,
  movingSpikeGeometryOverrideMaxReportedSpeedMetersPerSecond: 3.0,
  movingSpikeGeometryOverrideMinDetourMeters: 5,
  movingSpikeGeometryOverrideMinLateralMeters: 5,
  movingSpikeGeometryOverrideMaxForwardAngleDeltaDegrees: 30,
  movingSpikeMinDetourMeters: 1.5,
  movingSpikeMinLateralMeters: 2.5,
  movingSpikeMinNeighborDistanceMeters: 5,
  movingSpikeMaxBridgeDistanceMeters: 15,
  positionSnapRecoveryEnabled: true,
  positionSnapRecoveryMinWeakPoints: 2,
  positionSnapRecoveryMinBridgeDistanceMeters: 20,
  positionSnapRecoveryMaxReportedSpeedMetersPerSecond: 2,
  positionSnapRecoveryUnstablePrefixMinWeakPoints: 2,
  positionSnapRecoveryUnstablePrefixMinTransportPoints: 2,
  positionSnapRecoveryUnstablePrefixMaxTransportPoints: 4,
  positionSnapRecoveryUnstablePrefixMaxRawPointSpan: 8,
  positionSnapRecoveryUnstablePrefixMinDetourMeters: 20,
  positionSnapRecoveryUnstablePrefixMinReversalAngleDegrees: 120,
  positionSnapRecoveryUnstablePrefixMaxContinuationAngleDegrees: 30,
  positionSnapRecoveryUnstablePrefixMaxContinuationDistanceMeters: 60,
  denseAreaIntentEnabled: true,
  denseAreaIntentMinTrackPoints: 8,
  denseAreaIntentMaxSampleGapSeconds: 20,
  denseAreaIntentForwardMinNetDistanceMeters: 20,
  denseAreaIntentStationaryMaxNetDistanceMeters: 12,
  denseAreaIntentStationaryMaxBboxMeters: 35,
  denseAreaIntentStationaryMaxPathMeters: 60,
  denseAreaIntentRoundTripMinPathMeters: 80,
  denseAreaIntentRoundTripMaxNetPathRatio: 0.15,
  denseAreaIntentControlsMainRouteSettlement: true,
  denseMainRouteSettlementEnabled: true,
  denseMainRouteMinTrackPoints: 12,
  denseMainRouteMinNetDistanceMeters: 25,
  denseMainRouteMaxBboxMeters: 120,
  denseMainRouteMaxPathNetRatio: 3,
  denseMainRouteSimplifyToleranceMeters: 4,
  denseMainRouteMinPathReductionRatio: 0.15,
  forwardSpineArbitrationEnabled: true,
  forwardSpineSameDirectionMaxDeltaDegrees: 20,
  interwovenCorridorSimplifyEnabled: false,
  interwovenCorridorMinTrackPoints: 30,
  interwovenCorridorMinRawPointIdSpan: 200,
  interwovenCorridorMaxRawPointIdSpan: 600,
  interwovenCorridorMaxEndpointDistanceMeters: 6,
  interwovenCorridorMaxBboxMeters: 80,
  interwovenCorridorSimplifyToleranceMeters: 3,
  stationaryDistanceMeters: 5,
  stationaryAccuracyMultiplier: 1.5,
  stationaryCloudMinSamples: 2,
  slowMovementMinDistanceMeters: 2.5,
  lowAccuracyRescueMaxAccuracyMeters: 35,
  lowAccuracyRescueMinDistanceMeters: 2.5,
  continuityRescueMaxSpeedMetersPerSecond: 6,
  impossibleSpeedMetersPerSecond: 12,
  transportSpeedMetersPerSecond: 4.5,
  transportMinDistanceMeters: 20,
  locationAltitudeAscentMaxVerticalAccuracyMeters: 20,
  locationAltitudeAscentMinGainMeters: 1,
  locationAltitudeAscentMaxStepGainMeters: 30,
  barometerAscentMinGainMeters: 1,
  barometerAscentMaxSampleGapNanos: 30_000_000_000,
  barometerAscentMaxVerticalSpeedMetersPerSecond: 2,
  barometerPressureJumpMeters: 20,
  barometerCleaningEnabled: false,
  cloudTemporalDecaySeconds: 20
});

export function normalizeSixLayerTrackConfig(overrides = {}) {
  const config = { ...DEFAULT_SIX_LAYER_TRACK_CONFIG };
  for (const [key, value] of Object.entries(overrides || {})) {
    if (!(key in config)) continue;
    if (typeof config[key] === 'boolean') {
      config[key] = value === true;
    } else {
      const number = Number(value);
      if (Number.isFinite(number)) config[key] = number;
    }
  }
  return config;
}
